### ISSUE TITLE
Detect Pluto notebooks files in tutorial

### ISSUE THREAD

**Issue by VEZY** [rikhuijzer/JuliaTutorialsTemplate#16]
Thanks for the template it's very helpfull to make reproducible papers!

I just wonder if you would be open to add the possibility to add julia scripts that are not Pluto notebooks in the tutorial folder? I can make a PR if you're interested. 

Thanks again!

PS: here's our use case if you're wondering: 
We have a script that does a benchmark and a notebook for displaying the code and the results. We don't want to make the benchmark inside the notebook because it would take forever on Github's servers (and Pluto adds time), but we want people to be able to perform the benchmark if they want to, and we need to have it close to the notebook code, so inside the tutorial folder.

**Comment by rikhuijzer** [comment]
> Thanks for the template it's very helpfull to make reproducible papers!

I'm happy to hear that

> I just wonder if you would be open to add the possibility to add julia scripts that are not Pluto notebooks in the tutorial folder?

So, you mean before running the notebook to check whether it is a Pluto notebook? That already happens if you avoid specifying the files, that is, use 
```julia
build_notebooks(BuildOptions(dir))
```
instead of
```julia
build_notebooks(BuildOptions(dir), files)
```
see

https://github.com/rikhuijzer/PlutoStaticHTML.jl/blob/d3698bf9618e78986702dd2380ff5d604f2b722a/src/build.jl#L358-L380

>  We don't want to make the benchmark inside the notebook because it would take forever on Github's servers (and Pluto adds time)

How long is forever by the way? Especially since you mention that Pluto adds time. If your benchmark takes an hour, adding a few minutes for the Pluto runtime shouldn't be too bad. If your benchmark time is below an hour, then maybe running it in CI isn't too bad as long as you ensure that caching works.

**Comment by VEZY** [comment]
Hoo I'm sorry I'm running an older version of the Tutorial 🤦. Sorry for the inconvenience. 
The benchmark is not taking so long using the script, something like 10-20min, but when running from Pluto it was stuck even after one hour so I just killed it. Maybe I'm doing something wrong... I have to say we benchmark our package that is in Julia, another one in Julia but based on a Python package, and another one in R. So a lot of ways to fail. Right know I'm struggling to make Python work on the github action.

**Comment by rikhuijzer** [comment]
> Hoo I'm sorry I'm running an older version of the Tutorial facepalm. Sorry for the inconvenience.

No problem :slightly_smiling_face: 

> The benchmark is not taking so long using the script, something like 10-20min, but when running from Pluto it was stuck even after one hour so I just killed it. Maybe I'm doing something wrong...

I've had that happen to me too once. So okay I get it :+1: 

> Maybe I'm doing something wrong... I have to say we benchmark our package that is in Julia, another one in Julia but based on a Python package, and another one in R. So a lot of ways to fail. Right know I'm struggling to make Python work on the github action.

Then I said nothing. Getting R and/or Python to work in GitHub Actions is terrible!
