### ISSUE TITLE
CI / BuildAndDeploy Failed

### ISSUE THREAD

**Issue by mathutopia** [rikhuijzer/JuliaTutorialsTemplate#21]
Create a new repository based on this template failed when build notebooks.

some build error message follows

Run julia --project -e 'using Tutorials; build_tutorials()'
WARNING: Method definition process_preamble() in module WorkspaceManager at /home/runner/.julia/packages/Pluto/AgKPu/src/evaluation/WorkspaceManager.jl:26 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:55.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition show_richest(IO, Any) in module PlutoRunner at /home/runner/.julia/packages/Pluto/AgKPu/src/runner/PlutoRunner.jl:[1](https://github.com/mathutopia/dmtutorial/actions/runs/5241983918/jobs/9464789623#step:6:1)060 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:8.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition format_output(Base.CapturedException) in module PlutoRunner at /home/runner/.julia/packages/Pluto/AgKPu/src/runner/PlutoRunner.jl:954 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:45.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition kwcall(Any, typeof(Pluto.PlutoRunner.format_output), Base.CapturedException) in module PlutoRunner at /home/runner/.julia/packages/Pluto/AgKPu/src/runner/PlutoRunner.jl:954 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:45.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition kwcall(Any, typeof(Pluto.PlutoRunner.format_output), Base.CapturedException) in module PlutoRunner at /home/runner/.julia/packages/Pluto/AgKPu/src/runner/PlutoRunner.jl:954 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:45.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition process_preamble() in module WorkspaceManager at /home/runner/.julia/packages/Pluto/AgKPu/src/evaluation/WorkspaceManager.jl:26 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:55.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition format_output(Base.CapturedException) in module PlutoRunner at /home/runner/.julia/packages/Pluto/AgKPu/src/runner/PlutoRunner.jl:954 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:45.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition show_richest(IO, Any) in module PlutoRunner at /home/runner/.julia/packages/Pluto/AgKPu/src/runner/PlutoRunner.jl:1060 overwritten in module PlutoStaticHTML at /home/runner/.julia/packages/PlutoStaticHTML/7lLxj/src/mimeoverride.jl:8.
  ** incremental compilation may be fatally broken for this module **

[ Info: Cloning https://github.com/mathutopia/dmtutorial#gh-pages for caching purposes
Cloning into '/tmp/jl_ay29dr'...
warning: Could not find remote branch gh-pages to clone.
fatal: Remote branch gh-pages not found in upstream origin
[ Info: Starting evaluation of Pluto notebook benchmarking.jl
[ Info: Starting evaluation of Pluto notebook linear-model.jl
[ Info: Starting evaluation of Pluto notebook ode.jl
┌ Error: Pkg error: you might need to use
│ 
│ Pluto.reset_notebook_environment(notebook_path)
│ 
│ to reset this notebook's environment.
│ 
│ Before doing so, consider sending your notebook file to https://github.com/fonsp/Pluto.jl/issues together with the following info:
│   Pluto.PLUTO_VERSION = v"0.[19](https://github.com/mathutopia/dmtutorial/actions/runs/5241983918/jobs/9464789623#step:6:20).5"
│   VERSION = v"1.9.1"
│   exception =
│    MethodError: no method matching project_rel_path(::Pkg.Types.EnvCache, ::Nothing)
│    
│    Closest candidates are:
│      project_rel_path(::Pkg.Types.EnvCache, !Matched::String)
│       @ Pkg /opt/hostedtoolcache/julia/1.9.1/x64/share/julia/stdlib/v1.9/Pkg/src/Operations.jl:9[22](https://github.com/mathutopia/dmtutorial/actions/runs/5241983918/jobs/9464789623#step:6:23)

Error: Process completed with exit code 1.

**Comment by rikhuijzer** [comment]
Thanks for reporting this! I should have updated things. I've now updated a few things and I'll test tomorrow whether everything works now. Apologies for the delay

**Comment by rikhuijzer** [comment]
I've updated the dependencies and also tweaked the instructions a bit. Thanks again for reporting this issue and I hope it all works now. I'll close this issue, but feel free to make other issues or ask if there are more problems coming up
