### ISSUE TITLE
Newbie question: Used your template but problem with deployed website

### ISSUE THREAD

**Issue by feinmann** [rikhuijzer/JuliaTutorialsTemplate#8]
Hi there, I am quite new to github actions. I would be really glad if you could give me a hint, where I have to look. This is the deployment, I just used your template without changing anything:
https://feinmann.github.io/learn.jl/

I guess the css is not working. And there is a link refering to `JuliaTutorialsTemplate` as an repository of myself (so the naming was not adjusted, I guess).

Locally I could successfully build the tutorials and run also successfully.

Thanks for any comments and of course for this beautiful template.

**Comment by rikhuijzer** [comment]
Thank you for your question! I will give you some hints here. Can you try those and let me know if the hints don't work out?

In general, try to search for "JuliaTutorialsTemplate" in your repository. Each occurrence of that name is probably something you don't want to have! Note that the license is MIT, so you're free to change any text on the website. No need to point to JuliaTutorialsTemplate if you don't want

So, I searched for JuliaTutorialsTemplate via GitHub: https://github.com/feinmann/learn.jl/search?q=juliatutorialstemplate. The following things you probably would like to change:

1. Two occurrences are in `config.md`. That includes the `prepath`. Changing the `prepath` in your case to `learn.jl` should fix the CSS problem.
2. In the `README.md`, you probably want your own description of your project
3. The text `/JuliaTutorialsTemplate/` in `_layout/head` needs to be changed to your `learn.jl` too.

As a side-note, I saw that you added extra dependencies to the `Project.toml`. That's generally not necessary. The Pluto notebooks all have separate packages with the versions backed in. That way, you can change the version inside one notebook without having to change it everywhere. Also, it allows people to download the notebook (the link at the bottom of the page) and run it locally

Thanks again for your question. It is very valuable feedback.

**Comment by feinmann** [comment]
It is working!!! Replacing the occurences in 1. and 3. fixed the issues.

Thank you so much. The hint was exactly what I was looking for. I only start understanding github actions. But it works really well and I am super happy about your template, that I found through a thread on julialang discourse.

So far it is "only" for learning purposes.

Regarding the added dependency... I have to understand the package-system of julia a bit better. But when I tried the `build_tutorials()` locally, I got an error because of the missing package `OrdinaryDiffEq`... so I just added it. Also I got a warning that no specific julia-version is referenced in the `manifest`. Maybe I will understand later. (_Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version._)

Thank you!

**Comment by rikhuijzer** [comment]
> It is working!!! Replacing the occurences in 1. and 3. fixed the issues.

> Thank you so much. The hint was exactly what I was looking for. I only start understanding github actions. But it works really well and I am super happy about your template, that I found through a thread on julialang discourse.

Great to hear! No worries that it is just for testing. Your issue was helpful, I just made the template a bit easier to use thanks to your feedback (https://github.com/rikhuijzer/JuliaTutorialsTemplate/pull/9).

> Regarding the added dependency... I have to understand the package-system of julia a bit better. But when I tried the build_tutorials() locally, I got an error because of the missing package OrdinaryDiffEq... so I just added it.

That should not have happened and could mean that there is a bug in PlutoStaticHTML.jl. Very weird. I'll keep an eye on it

> Also I got a warning that no specific julia-version is referenced in the manifest. Maybe I will understand later. (Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.)

That's because you're running Julia 1.7 and I was running 1.6 while creating the tutorials. Good point also, I'll re-run the tutorials with Julia 1.7 to fix that for other people. EDIT: Done (https://github.com/rikhuijzer/JuliaTutorialsTemplate/pull/10)
